apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app-container
    image: my-app-image
    volumeMounts:
    - name: app-volume
      mountPath: /data
  volumes:
  - name: app-volume
    hostPath:
      path: /var/lib/app