apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: secret-volume
          mountPath: /redis/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret